project_dir: '/home/andyb/MutationRates/faststorage/Andrej'
chromosomes: 'chr1,chr2A,chr2B,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22'
generic_input_vcf: '/home/andyb/MutationRates/faststorage/Andrej/data_hard_filter/split/chimp.raw.pure.CHROMOSOME.vcf.gz'
# generic_input_vcf: '/home/andyb/MutationRates/faststorage/Andrej/data_soft_filter/CHROMOSOME/chimp.raw.pure.vcf.gz'
hapi_exe: '/home/andyb/MutationRates/faststorage/Andrej/mutation_rates/tools/hapi/hapi-mr'
pedigree: '/home/andyb/MutationRates/faststorage/Andrej/data_hapi_approach/chimp.numbered.pedigree'
